### ISSUE TITLE
Lv - Lokomotívny vlak

### ISSUE THREAD

**Issue by flegmatematik** [flegmatematik/BC_Lukas_Loffler_OdhadVlakovychSuprav#10]
Včera sme sa bavili o tej filtrácií, a napadlo ma, že či do toho modelu zaradiť aj vlaky typu Lv.
Je to akoze iba viacero lokomotiv dokopy, a teda nieje to vlak co by nieco prevazal, skor manipulacny presun. Tak podla mna ho nieje treba, lebo práve tam sa nachádza veľa tých vlakov ktoré majú iba jeden vagón (neviem ci CarCount zahŕňa aj hanciu lokomotívu), ale na druhú stranu, tých údajov je tam 120 000, tak neviem.

**Comment by flegmatematik** [comment]
Rovnako aj Sluz 
![obrázok](https://user-images.githubusercontent.com/50167380/78450724-0120b180-7681-11ea-818e-62a741fa09c8.png)

**Comment by KelloTomas** [comment]
Ak su udaje konzistentne, zaradil by som ich do vstupnej mnoziny. Teda jazdna doba je priblizne rovnaka. CarCount niekedy pocita aj lokomotivu, inokedy nie. Zalezi na zadavatelovi.

Takze pozrel by som si rozptyl jazdnych dob na trati. Ak je to rozumne, tak nechal. Ak su uplne rozhadzane, ze raz mu cesta trva 1min inokedy 8min tak to vsetko vymazal (obe moznosti opisat do prace a preco si sa pre ktoru rozhodol ZAHRNUT/NEZAHRNUT)

**Comment by flegmatematik** [comment]
Rozhodol som sa to ponechať. Postupne v každom okresaní dát je menej typov vlakov, ale okresávam to na základe iných znakov.
