### ISSUE TITLE
neparny pocet naprav

### ISSUE THREAD

**Issue by KelloTomas** [flegmatematik/BC_Lukas_Loffler_OdhadVlakovychSuprav#2]
Bud je to chyba alebo si pozri konkretny zaznam, ci nema prehodene stlpce dlzka, pocet naprav/vagonov.

Vzdy je to v postupke od najmensieho. Pocet vagonov, naprav, vaha

tento vztah ti vie celkovo vela odhalit a opravit kopec chyb ci chybajucich hodnot (vsetko zapis do teorie)

**Comment by flegmatematik** [comment]
Super, to som si nevšimol, máš pravdu. Niektoré stĺpce sú naozaj prehodené, a potom už dávajú zmysel. Ďakujem za tip

**Comment by KelloTomas** [comment]
Nie je to vzdy, niekedy aj nepadne hodnoty su.... Bud to mozes vyhodnotit ako chybu a nastavit mu tam NULL alebo dopocitat cez pocet vagonov. Dolezite, aby si vsetko pisal do teorie. Co si nasiel ako to chces riesit a co ocakavas ze tym dosiahnes a ci si naozaj dosiahol (ked budes mat model, ten ti definuje ako dobre sa naucil zo vstupnych dat. Takze cim lepsie data, tym sa lepsie nauci)
