### ISSUE TITLE
posun casu letny <-> zimny

### ISSUE THREAD

**Issue by KelloTomas** [flegmatematik/BC_Lukas_Loffler_OdhadVlakovychSuprav#4]
Ten datum aj hodinu si vies presne vyhladat na googli. Samozrejme pre kazdy rok je ten datum iny.

meskanie sa neobjavi, je to ocakavane aj naplanovane s posunom. Jedine bude odchod 2:55 a prichod 2:01 napriklad. Takze zaporna jazdna doba. Sprav si SELECT a zisti ako sa spravali vlaky a ake su zaznamy v tomto presune. Ja si to uz nepametam ale robil som s tym uz

**Comment by flegmatematik** [comment]
Táto časť čistenia dát mi príde až nemožná. Pretože veľa dát má príliš rozličné chyby, ktoré sa mi zatiaľ nepodarilo odčleniť. 
Tento select napríklad ukazuje, že počas zmeny na letný čas, kedy by od 2:00 - 3:00 nemali byť žiadne hodnoty to skáče z 3:06->2:10
a potom 2:14 ->3:20

Select FromName, ToName, TrainId, TrainNumber, TrainType, DepPlanTime, ArrPlanTime, DepRealTime, ArrRealTime
  FROM [TrainsDb20-01-23].[dbo].[CZ-PREOS_GTN]
  where TrainId = 2035967
  and ArrILS =1
  and DepILS =1
    order by TrainId,SectIdx ASC

Takže nemôžem ľahko nájsť tie prechodové časti, kde by som vedel to meškanie odstrániť. Ale hľadám naďalej

**Comment by KelloTomas** [comment]
Evidentne niektore zabezpecovacky funguju na novom/starom čase. Riešenia:
jednoduche:
- Vymazať všetky v deň zmeny času.
- Vymazať všetky v rozsahu +-1h
- vypočítať jazdnú dobu, v prípade zápornej sa s nou pohrať, či jej nepomôže pridať 1h k prijazdu
- Vymazať všetky záznamy so zápornou jazdnou dobou /aj v inom období ako počas zmeny času, ale zisťiť aspoň orientačne, kedy a kde nastávajú záporné jazdné doby. Ak ich nie je vela tak je to v pohode/

**Comment by flegmatematik** [comment]
+- Vyriešené. Väčšina údajov bola zachránená a boli upravené, ostatné, ktorým sa nedalo určiť, či meškajú/idú priskoro alebo či ich ovplyvnil posun času, boli odstránené. 
Našiel som všetky údaje z časového okna kedy nastáva posun času a natiahol ho na takú dobu, kde sa ešte nachádzali vlaky ktoré boli zmenou času ovplyvnené -> buď mali oproti plánovanému času hodinové meškanie, alebo o hodinu prišli skôr. Nastavil som časovú podmienku do ktorej padli približne iba tie vlaky teda ich rozdiel bol 1 hodina +- nejaké minúty. Bohužiaľ, ak vlak bol ovplyvnený posunom, a meškal približne 1 hodinu, tak sa javil ako vlak, ktorý nemešká a teda takýto údaj som nevedel opraviť. Koniec koncov, Iba zopár vlakov bolo týmto ovplyvnené, ale už by nemali robiť problém.
