### ISSUE TITLE
Meškania niektorých vlakov sú príliš obrovké, ale niesú nezastúpené

### ISSUE THREAD

**Issue by flegmatematik** [flegmatematik/BC_Lukas_Loffler_OdhadVlakovychSuprav#6]
Veľa jázd má meškanie aj viac ako deň - samozrejme platí iba pre nákladné vlaky. Má nejaký zmysel ich skúmať? Rozmýšľal som, či tie údaje neokresať podľa nejakých hraníc. Že maximálne meškanie bude 12 hodín a aj záporné meškanie bude maximálne 12 hodín. Ale Takýchto vlakov je 80 000. Ich percentá meškania sú tiež cez strop. Tak neviem, či je dobrý nápad, ich takto odfiltrovať. Uľahčilo by to veci, ale na druhú stranu by to malo asi veľký dopad na to, ako by model vedel predikovať práve tie obrovské meškania. Zatiaľ som presvedčený ich tam nechať, len ma zaujíma čo na to ty hovoríš.

**Comment by KelloTomas** [comment]
dispecerom sa asi nechce nastavovat vlaky tak vyslu vlak ako hocijaky iny (moj odhad) preto meska aj dva tri dni.... Len ho potrebuju zaevidovat. A co ta jeho jazdna doba. Je normalna alebo ide aj vyrazne pomalsie/rychlejsie?

Rozumne je to nechat, alebo spravit vlastnu skupinu vlakov, ktore mali velke meskanie

Alebo spravit transformaciu. Uz zacali svoju celu trasu s meskanim? Vtedy len posunut planovanu trasu o dany cas. Ale ak v polovici zastal a stal niekde den, to by sa uz posuvat nemalo :/

**Comment by KelloTomas** [comment]
Posli databazu, ID riadku, ID vlaku aspon niektorych, nech sa na to pozriem

**Comment by flegmatematik** [comment]
Select: 

SELECT [Id]
	  ,[TrainId]
      ,[FromName]
      ,[ToName]
      ,[TrainType]
      ,[Weight]
      ,[Length]
      ,[CarCount]
      ,[AxisCount]
      ,SUBSTRING([EngineType],1,4) as EngineType
	  ,[DepPlanTime]
	  ,[ArrPlanTime]
	  ,[DepRealTime]
	  ,[ArrRealTime]	  
      ,DATEDIFF(SECOND,'1970-01-01',[DepRealTime]) as DepRealTime
      ,DATEDIFF(SECOND,'1970-01-01',[ArrRealTime]) as ArrRealTime
      ,DATEDIFF(SECOND,[DepRealTime],[ArrRealTime]) as RealDrivingTime
      ,DATEDIFF(SECOND,'1970-01-01',[DepPlanTime]) as DepPlanTime
      ,DATEDIFF(SECOND,'1970-01-01',[ArrPlanTime]) as ArrPlanTime
      ,DATEDIFF(SECOND,[DepPlanTime],[ArrPlanTime]) as PlanDrivingTime
      ,COALESCE([LengthSect],0) as LengthSect
      ,COALESCE([PredLength],0) as PredLength
  FROM [TrainsDb20-01-23].[dbo].[CZ-PREOS_GTN] 
  where DepPlanTime IS NOT NULL
  and DepRealTime IS NOT NULL
  and ArrRealTime IS NOT NULL
  and ArrPlanTime IS NOT NULL
  and CarCount > 0
  and AxisCount > 0
  and FromName <> ToName
  and DATEDIFF(SECOND,DepPlanTime,ArrPlanTime) > 60 
  and DATEDIFF(SECOND,[DepRealTime],[ArrRealTime]) > 0
  and DATEDIFF(SECOND,[DepPlanTime],[ArrPlanTime]) > 0
  and ABS(DATEDIFF(SECOND,[ArrRealTime],[DepRealTime]) - DATEDIFF(SECOND,[ArrPlanTime],[DepPlanTime])) > 15000
  and (DATEDIFF(SECOND,'1970-01-01',[ArrRealTime]) - DATEDIFF(SECOND,'1970-01-01',[DepRealTime])) <> 0

Pozri si PlanDrivingTime a RealDrivingTime 

Zle som sa vyjadril, to je moja chyba. Myslel som skôr z pohľadu jazdných dôb, že keď mal vlak ísť 5 minút ale miesto toho je jeho jazdná doba dlhšia. Alebo naopak, keď plánovaná doba je príliš dlhá a vlak to stihne za oveľa kratší čas(v tomto prípade je to jasná chyba lebo tie hodnoty sú obrovské). Ja len neviem, že či vlaky často čakajú v polke svojej trasy, a či skôr nečakajú na staniciach.
